import { Inter } from "next/font/google";
import styles from "./page.module.css";

const inter = Inter({ subsets: ["latin"] });
import "./globals.css";
import Footer from "@/components/ui/footer/home/Footer";
import HomeNav from "@/components/ui/nav/home/HomeNav";
import Player from "@/components/ui/player/Player";
export const metadata = {
  title: "Block",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <>
          <>
            <Player />
            <>
              <HomeNav />
            </>
          </>
          {children}
          <Footer />
        </>
      </body>
    </html>
  );
}
