
import NewsNav from "@/components/ui/nav/news/NewsNav";
import './layout.css'
export const metadata = {
    title: "Block - Inside Block",
    description: "Generated by create next app",
  };

export default function NewsLayout({ children }) {

  return (
    <body >
      <div className="sticky" style={{
            zIndex: 2
          }}>
          <div className="margin center" >
            <NewsNav />
          </div>
      </div>
        {children}
    </body>
  );
}
